### ISSUE TITLE
Update vecty tag

### ISSUE THREAD

**Issue by julienrbrt** [hexops/vecty#273]
Due to the change of path a `go get github.com/hexops/vecty` will result in a

```
go: github.com/hexops/vecty upgrade => v0.5.0
go get: github.com/hexops/vecty@v0.5.0: parsing go.mod:
        module declares its path as: github.com/gopherjs/vecty
                but was required as: github.com/hexops/vecty
```

`go get github.com/hexops/vecty@master` fixes the issue but it would be nice if a new tag is created to avoid this workaround.

**Comment by slimsag** [comment]
Thank you for calling this out! Will push up a new tag soon.

**Comment by slimsag** [comment]
Fixed via e5d44d29c6a6bea841570b7708ad9a00c87d704d

**Comment by julienrbrt** [comment]
It does not seems to be created: https://github.com/hexops/vecty/tags

**Comment by nfrush** [comment]
@slimsag This isn't fixed. There is no other tags on this repo outside of v0.5.0. Seems you need to cut v0.6.0 again.

**Comment by slimsag** [comment]
@julienrbrt @nfrush so sorry for missing this 😞 I have just pushed the tag up, my mistake - hope this didn't cause you too much trouble!
